name: Docker Build

on:
  push:
    branches:
      - main

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  build_docker_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64  # Specify the platforms here
          push: true
          tags: medhansh37/minorproject-sundown:latest

      - name: Slack Notification on Success
        if: ${{ always() && success() }}
        uses: act10ns/slack@v1
        with: 
          status: ${{ job.status }}
          channel: '#cicd-pipeline'
          message: "Deployed ${{ github.ref }} branch Successfully"

      - name: Slack Notification on Failure
        if: ${{ always() && failure() }}
        uses: act10ns/slack@v1
        with: 
          status: ${{ job.status }}
          channel: '#cicd-pipeline'
          message: |
            Deployment failed for ${{ github.ref }} branch.
            Error details: ${{ job.status }}

      - name: Slack Notification on Error
        if: ${{ always() && cancelled() }}
        uses: act10ns/slack@v1
        with: 
          status: ${{ job.status }}
          channel: '#cicd-pipeline'
          message: |
            Job cancelled for ${{ github.ref }} branch.
            Error details: ${{ job.status }}
