name: Docker Build

on:
  push:
    branches:
      - main
env:
 SLACK_WEBHOOK_URL: ${{ secret.SLACK_WEBHOOK_URL}}
      

jobs:
  build_docker_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: medhansh37/minorproject-sundown:latest
          
      - name: Slack Notification
        uses: act10ns/slack@v1
        with: 
         status: ${{ job.status }}
         channel: '#meetups'
         message: Deployed {{ env.GITHUB_REF_NAME }} branch Successfully
        if: always()    
      
       

 
          
