name: Build and Notify

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: medhansh37/minorproject-sundown:latest

  notify_slack:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Send notification to Slack
        uses: rtCamp/action-slack-notify@v2
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          message: "Git push done in the repo, MinorProject"
