name: Build and Notify

on:
  push:
    branches:
      - main

jobs:
  build_and_notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: medhansh37/minorproject-sundown:latest

      - name: Send notification to Slack
        uses: rtCamp/action-slack-notify@v2
        with:
          slack_webhook: https://hooks.slack.com/services/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
          message: "Git push done in the repo, MinorProject"
